package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-macosx-x86_64/jdk8u73/6086/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Friday, January 29, 2016 3:03:47 PM PST
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
  	 * The value representing ID_UNIQUENESS_POLICY_ID.
  	 */
  public static final int value = (int)(18L);
}
